### Find all products
Get http://localhost:8080/products

### Find a product by id 
GET http://localhost:8080/products/3

### Find products by category
GET http://localhost:8080/products/category/accessory

### Create a product
Post http://localhost:8080/products/create
Content-Type: application/json

{
    id: 2,
    name: "Fancy chair",
    image: "/images/img1.jpg",
    brand: "Fako",
    category: "Accessoires",
    description: "This is a very fancy product from Fako brand",
    price: 20.99,
    countInStock: 21,
    rating: 4,
}

### delete product 
DELETE http://localhost:8080/products/delete/9